INSERT INTO CategoriaControlesImplementar (id, nombre)
VALUES (1, 'ORGANIZACIONALES'),
       (2, 'PERSONAS'),
       (3, 'FÍSICOS'),
       (4, 'TECNOLÓGICOS');

INSERT INTO ControlesImplementar (seccion, descripcion, categoriaid)
VALUES ('1.1', 'Políticas de seguridad de la información (específicas)', 1),
       ('1.2',	'Roles y Responsabilidades de Seguridad de la Información', 1),
       ('1.3',	'Separación de Funciones', 1),
       ('1.4',	'Responsabilidades de la dirección', 1),
       ('1.5',	'Contacto con las autoridades', 1),
       ('1.6',	'Contacto con grupos de interés especial', 1),
       ('1.7',	'Inteligencia de amenazas', 1),
       ('1.8',	'Seguridad de la información en la Gestión de proyectos', 1),
       ('1.9',	'Inventario de información y otros activos asociados', 1),
       ('1.10',	'Uso aceptable de la información y otros activos asociados', 1),
       ('1.11',	'Devolución de activos', 1),
       ('1.12',	'Clasificación de la información', 1),
       ('1.13',	'Etiquetado de la información', 1),
       ('1.14',	'Transferencia de información', 1),
       ('1.15',	'Control de Acceso', 1),
       ('1.16',	'Gestión de Identidad', 1),
       ('1.17',	'Información de autenticacion', 1),
       ('1.18',	'Derechos de acceso', 1),
       ('1.19',	'Seguridad de la información en las relaciones con proveedores', 1),
       ('1.20',	'Abordar la seguridad de la información en los acuerdos con proveedores', 1),
       ('1.21',	'Gestión de la seguridad de la información en la cadena de suministro de las TIC', 1),
       ('1.22',	'Monitoreo, revisión y gestión de cambios de servicios de proveedores.', 1),
       ('1.23',	'Seguridad de la información para el uso de servicios en la nube', 1),
       ('1.24',	'Planificación y preparación de la gestión de incidentes de seguridad de la información', 1),
       ('1.25',	'Evaluación y decisión sobre eventos de seguridad de la información', 1),
       ('1.26',	'Respuesta a incidentes de seguridad de la información', 1),
       ('1.27',	'Aprendiendo de los incidentes de seguridad de la información', 1),
       ('1.28',	'Recopilación de evidencias', 1),
       ('1.29',	'Seguridad de la Información durante la interrrución', 1),
       ('1.30',	'Preparación de la TIC para la continuidad del Negocio ', 1),
       ('1.31',	'Requisitos legales, estatutarios, reglamentarios y contractuales', 1),
       ('1.32',	'Derechos de propiedad intelectual', 1),
       ('1.33',	'Protección de los registros', 1),
       ('1.34',	'Privacidad y protección de PII', 1),
       ('1.35',	'Revisión independiente de seguridad de la información', 1),
       ('1.36',	'Cumplimiento de políticas, reglas y normas de seguridad de la información', 1),
       ('1.37',	'Procedimientos operativos documentados', 1),
       ('2.1',	'Selección', 2),
       ('2.2',	'Términos y condiciones de empleo, documentado e implementado', 2),
       ('2.3',	'Concienciación, educación y formación en seguridad de la información, documentado e implementado', 2),
       ('2.4',	'Proceso disciplinario, documentado e implementado', 2),
       ('2.5',	'Responsabilidades después de la terminación o cambio de empleo, documentado e implementado', 2),
       ('2.6',	'Acuerdo de confidenciliadad o no divulgación, documentado e implementado', 2),
       ('2.7',	'Trabajo remoto', 2),
       ('2.8',	'Reporte de eventos de seguridad de la información', 2),
       ('3.1',	'Perímetros de seguridad física', 3),
       ('3.2',	'Entrada física', 3),
       ('3.3',	'Seguridad de oficinas, despachos e instalaciones', 3),
       ('3.4',	'Monitoreo de seguridad física', 3),
       ('3.5',	'Protección contra las amenazas externas y ambientales', 3),
       ('3.6',	'Trabajo en áreas seguras', 3),
       ('3.7',	'Puesto de trabajo despejado y pantalla limpia', 3),
       ('3.8',	'Ubicación y protección de equipos', 3),
       ('3.9',	'Seguridad de los activos fuera de las instalaciones', 3),
       ('3.10',	'Medios de almacenamiento', 3),
       ('3.11',	'Servicios de Soporte', 3),
       ('3.12',	'Seguridad del cableado', 3),
       ('3.13',	'Mantenimiento de equipo', 3),
       ('3.14',	'Eliminación segura o reutilización de equipos', 3),
       ('4.1',	'Dispositivos de usuario final', 4),
       ('4.2',	'Derechos de acceso privilegiado', 4),
       ('4.3',	'Restricción de acceso a la información', 4),
       ('4.4',	'Acceso al código fuente', 4),
       ('4.5',	'Autenticación Segura', 4),
       ('4.6',	'Gestión de la capacidad', 4),
       ('4.7',	'Proteccion contra malware', 4),
       ('4.8',	'Gestión de vulnerabilidades técnicas', 4),
       ('4.9',	'Gestión de la Configuración', 4),
       ('4.10',	'Eliminación de información', 4),
       ('4.11',	'Enmascaramiento de datos', 4),
       ('4.12',	'Prevención de fuga de datos', 4),
       ('4.13',	'Copia de seguridad de la información', 4),
       ('4.14',	'Redundancia de las instalaciones de tratamiento de información', 4),
       ('4.15',	'Registros de eventos', 4),
       ('4.16',	'Actividades de monitoreo', 4),
       ('4.17',	'Sincronización de reloj', 4),
       ('4.18',	'Uso de programas de utilidad privilegiados', 4),
       ('4.19',	'Instalación de software en sistemas operativos', 4),
       ('4.20',	'Seguridad de redes', 4),
       ('4.21',	'Seguridad de los servicios de red.', 4),
       ('4.22',	'Separación en las redes', 4),
       ('4.23',	'Filtrado web', 4),
       ('4.24',	'Uso de criptografía', 4),
       ('4.25',	'Ciclo de vida de desarrollo seguro', 4),
       ('4.26',	'Requisitos de seguridad de la aplicación', 4),
       ('4.27',	'Arquitectura del sistema seguro y principios de ingeniería', 4),
       ('4.28',	'Codificación Segura', 4),
       ('4.29',	'Pruebas de seguridad en el desarrollo y la aceptación', 4),
       ('4.30',	'Desarrollo subcontratado', 4),
       ('4.31',	'Separación de los entornos de desarrollo, prueba y producción', 4),
       ('4.32',	'Gestión de cambios', 4),
       ('4.33',	'Información de prueba', 4),
       ('4.34',	'Protección de los sistemas de información durante las pruebas de auditoría', 4)
;